apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: inari
  namespace: argocd
spec:
  description: Inari-managed applications (e2e)
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
